housekeeping_genes: ["GAPDH", "RNAseP", "B2M", "ACTB"]
thresholds:
  eGFP: 0.1
  RNAseP: 0.05
  GAPDH: None
  B2M: None
plot_properties:
  transparent: False
  dpi: 600
input_file_name: "Results - Copy.xls"